---
sidebar: sidebar 
permalink: concept-privacy.html 
keywords: privacy, data privacy, credentials, access to credentials, hashicorp vault 
summary: 'NetApp non ha accesso alle credenziali fornite durante l"utilizzo di NetApp Copy and Sync.  Le credenziali vengono memorizzate direttamente sulla macchina del broker di dati, che risiede nella tua rete.' 
---
= Privacy dei dati in NetApp Copy and Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp non ha accesso alle credenziali fornite durante l'utilizzo di NetApp Copy and Sync.  Le credenziali vengono memorizzate direttamente sulla macchina del broker di dati, che risiede nella tua rete.

A seconda della configurazione scelta, Copia e sincronizzazione potrebbe richiedere le credenziali quando si crea una nuova relazione.  Ad esempio, quando si imposta una relazione che include un server SMB o quando si distribuisce il broker di dati in AWS.

Queste credenziali vengono sempre salvate direttamente sul data broker stesso.  Il broker di dati risiede su una macchina nella tua rete, sia in locale che nel tuo account cloud.  Le credenziali non vengono mai rese disponibili a NetApp.

Le credenziali vengono crittografate localmente sulla macchina del broker di dati tramite HashiCorp Vault.
