---
settings:
  name: NetApp Copy and Sync
  harmony_integration: maestro
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione NetApp Copy and Sync
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Cosa c'è di nuovo
      url: "/whats-new.html"
    - title: Limitazioni
      url: "/reference-limitations.html"
  - title: Iniziare
    entries:
    - title: Scopri di più su NetApp Copy and Sync
      url: "/concept-cloud-sync.html"
    - title: Avvio rapido
      url: "/task-quick-start.html"
    - title: Visualizza le relazioni di sincronizzazione supportate
      url: "/reference-supported-relationships.html"
    - title: Preparare la sorgente e la destinazione
      url: "/reference-requirements.html"
    - title: Preparare il networking
      url: "/reference-networking.html"
    - title: Accedi a NetApp Copy and Sync
      url: "/task-login-copyandsync.html"
    - title: Installare un broker di dati
      entries:
      - title: Installa in AWS
        url: "/task-installing-aws.html"
      - title: Installa in Azure
        url: "/task-installing-azure.html"
      - title: Installa in Google Cloud
        url: "/task-installing-gcp.html"
      - title: Installa su un host Linux
        url: "/task-installing-linux.html"
  - title: Utilizzare NetApp Copy and Sync
    entries:
    - title: Sincronizzare i dati tra un'origine e una destinazione
      entries:
      - title: Preparare un broker di dati per sincronizzare i dati tra gli archivi
          di oggetti
        url: "/task-prepare-object-storage.html"
      - title: Crea una relazione di sincronizzazione
        url: "/task-creating-relationships.html"
      - title: Copia ACL da una condivisione SMB
        url: "/task-copying-acls.html"
      - title: Crittografare i dati NFS in transito
        url: "/task-nfs-encryption.html"
      - title: Utilizza i segreti di HashiCorp Vault
        url: "/task-external-vault.html"
    - title: Impostare la licenza
      url: "/task-licensing.html"
    - title: Gestisci le relazioni di sincronizzazione
      url: "/task-managing-relationships.html"
    - title: Gestire i broker di dati
      url: "/task-managing-data-brokers.html"
    - title: Visualizza i report per ottimizzare la tua configurazione
      url: "/task-managing-reports.html"
    - title: Disinstallare un broker di dati
      url: "/task-uninstalling.html"
  - title: Automatizza con l'API REST
    url: "/api-sync.html"
  - title: Concetti
    entries:
    - title: Licenza
      url: "/concept-licensing.html"
    - title: Privacy dei dati
      url: "/concept-privacy.html"
    - title: Domande frequenti
      url: "/faq.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere supporto
      url: "/task-support-registration.html"
    - title: Ottieni aiuto
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
